### ISSUE TITLE
 ㅈㄴ때리고싶네ㄹㅇ

### ISSUE THREAD

**Issue by elcodeofficial-kr** [KimDongSin/Pokedex#2]
ㄹㅇ

![image](https://github.com/user-attachments/assets/ba7570f6-8e00-435e-8b98-a09307681d10)

**Comment by KimDongSin** [comment]
딱대라

**Comment by elcodeofficial-kr** [comment]
![l_2012043001004055300311093](https://github.com/user-attachments/assets/3219bf90-fb87-4d22-b636-1602fc6ce819)

**Comment by elcodeofficial-kr** [comment]
![viewimageM](https://github.com/user-attachments/assets/24e36c5b-ac27-4393-af10-2dd64c6a4b94)
